modLoader="javafml"
loaderVersion="[1,)" # NeoForge uses same FML but newer system
license="All Rights Reserved"

[[mods]]
modId="geminigod"
version="2.0.0"
displayName="GeminiGod"
description='''A god-like Gemini AI that interacts with the Minecraft world.'''

[[dependencies.geminigod]]
modId="neoforge"
mandatory=true
versionRange="[20.2.88,)"
ordering="NONE"
side="BOTH"

[[dependencies.geminigod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
